
image:
    file: .gitpod.Dockerfile

tasks:
  - name: Supabase Installation
    init: supabase start
    command: 
      supabase status -o env | sed 's/^/SUPABASE_/' > .env # Copies local dev environment in .env

ports:
  - name: Supabase
    description: Frontend of the Supabase
    port: 54323
    onOpen: open-browser
  - name: API
    description: API Endpoint
    port: 54321
    visibility: public
    onOpen: ignore


vscode:
  extensions:
    - denoland.vscode-deno