
image:
    file: .gitpod.Dockerfile

tasks:
  - name: Supabase Installation
    init: supabase start
    command: supabase status -o env | sed 's/^/SUPABASE_/' > .env # Copies local dev environment in .env

ports:
  - name: Supabase
    description: Frontend of the Supabase
    port: 54323
    onOpen: open-browser


vscode:
  extensions:
    - denoland.vscode-deno