
image:
    file: .gitpod.Dockerfile

tasks:
  - name: Supabase Installation
    init: supabase init
    command: |
      supabase start
      # Extract environment variables from supabase CLI, write to .env
      supabase status -o env | sed 's/^/SUPABASE_/' > .env
      # Load .env variables
      if [ -f .env ]; then
        export $(grep -v '^#' .env | xargs)
      fi

ports:
  - name: Supabase
    description: Frontend of the Supabase
    port: 54323
    onOpen: open-preview
  - name: API
    description: API Endpoint
    port: 54321
    visibility: public
    onOpen: ignore


vscode:
  extensions:
    - denoland.vscode-deno