image:
    file: .gitpod.Dockerfile

tasks:
  - name: Script Task
    init: supabase start

ports:
  - name: Supabase
    description: Frontend of the Supabase
    port: 54323
    onOpen: open-browser

